spring:
  application:
    name: microservico-1

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
      instance-id: ${spring.application.name}:${random.int}

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true