spring:
  application:
    name: zuul-server

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${random.int}

zuul:
  routes:
    MICROSERVICO-1: /ms1/**
    MICROSERVICO-2: /ms2/**
    MICROSERVICO-3: /ms3/**